module.exports = [
    "JavaScript",
    "TypeScript",
    "C++",
    "Python",
    "React",
    "React Native",
    "Angular",
    "Node.js",
    "Express.js",
    "MongoDB",
    "Firebase",
    "Docker",
    "Linux",
    "Git",
    "GitHub",
    "REST APIs",
    "RxJS",
    "HTML",
    "CSS",
];